### ISSUE TITLE
Questions about the universality of algorithms

### ISSUE THREAD

**Issue by LAY-77** [doloMing/Transfer-entropy-spectrum-in-the-Fourier-domain#2]
Is the method spectrum-based, and is it convincing if the   surrogate is used to calculate similar results to the original data?

**Comment by doloMing** [comment]
Our approach in the paper as well as in the matlab code is calculated based on time-frequency representation (e.g., a wavelet power spectrum). So you can generally say that our approach is spectrum-based. Surrogates can be used in calculating results. In fact, the statistics test of calculated transfer entropy is implemented based on a surrogate method. Similar methods are common in permutation test. Please feel free to contact me if you have questions in practice (e.g., when you use surrogates).Best,Yang ---- Replied Message ***@***.***>Date03/29/2022 20:14 ***@***.***> ***@***.***>Subject[doloMing/Transfer-entropy-spectrum-in-the-Fourier-domain] Questions about the universality of algorithms (Issue #2)
Is the method spectrum-based, and is it convincing if the   surrogate is used to calculate similar results to the original data?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/doloMing/Transfer-entropy-spectrum-in-the-Fourier-domain/issues/2",
"url": "https://github.com/doloMing/Transfer-entropy-spectrum-in-the-Fourier-domain/issues/2",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
